kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-gitlab02
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/pv-gitlab02
  persistentVolumeReclaimPolicy: Recycle
