kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-gitlab03
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/pv-gitlab03
  persistentVolumeReclaimPolicy: Recycle
