kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-prom01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /tmp/pv-prom01
  persistentVolumeReclaimPolicy: Recycle
